export const INIT_EVENT_LIST = 'INIT_EVENT_LIST';
export const ADD_EVENT = 'ADD_EVENT';
export const SET_CURRENT_EVENT = 'SET_CURRENT_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';
export const SET_IS_TIMING = 'SET_IS_TIMING';
export const ADD_TIMING_RECORD = 'ADD_TIMING_RECORD';
export const TOOGLE_EVENT_DONE = 'TOOGLE_EVENT_DONE';
